config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/privacy', to: "users#privacy"
  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  get   'contact'         => 'contact#index'     # 入力画面
  post  'contact/confirm' => 'contact#confirm'   # 確認画面
  post  'contact/thanks'  => 'contact#thanks'    # 送信完了画面
  
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  resources :users
  resources :videos
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    url = params[:video][:youtube_url]
    url = url.last(11) #Youtubeのurlの下11文字を取得する
    @video.body = url
    if @video.save
      flash[:success] = '新規作成に成功しました。'
      render :index
    else
      render :new
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    url = params[:video][:youtube_url]
    url = url.last(11)
    @video.youtube_url = url
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to videos_url, notice: 'Video was successfully updated.' }
        format.json { render :index, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :youtube_url)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: @video, local: true) do |f| %>
  <%= render 'share/error_messages' , object: @video %>

  <%= f.label :title, class: "label-signup" %> <span class="must">必須</span>
  <%= f.text_field :title, placeholder: "例)好きな動画", class: "form-control" %>

  <%= f.label :youtube_url, class: "label-signup" %> <span class="must">必須</span>
  <%= f.text_field :youtube_url, placeholder: "YoutubeのURLを貼り付けてください", class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-signup" %>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<% provide(:title, 'Video 一覧') %>
<div class="tool-index-body">
<div class="container">
  <h1>動画</h1>
  <div class="row" >
    <div class="col-md-8 col-md-offset-2">
      <% if @videos.count < 1 %><%#= データの数で %>
        <h1>只今、準備中。</h1>
          <div class="col-md-8 col-md-offset-2">
            <div class="botton2">
              <td>
                <%= link_to "ホームへ", root_path, class: "btn btn-lg btn-primary" %>
              </td>
                <td>
                  <%= link_to "新規追加", new_video_path, class: "btn btn-lg btn-primary" %>
                </td>
            </div>
          </div>
      <% else %>
        <% @videos.each do |video| %>
          <div class="title">
            <p>タイトル：<%= video.title %></p>
          </div>
          <div class="video">
            <iframe width="750" height="500" src="https://www.youtube.com/embed/<%= video.body %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
            <div class="botton">
              <td>
                <%= link_to "編集", edit_video_path(video), class: "btn btn-lg btn-primary" %>
              </td>
              <td>
                <%= link_to "削除", video , method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-lg btn-danger" %>
              </td>
            </div>
        <% end %>
          <div class="col-md-8 col-md-offset-2">
            <div class="botton2">
              <td>
                <%= link_to "ホームへ", root_path, class: "btn btn-lg btn-info" %>
              </td>
                <td>
                  <%= link_to "新規追加", new_video_path, class: "btn btn-lg btn-info" %>
                </td>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<% provide(:title, "Show Video") %>
<h1>動画詳細</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-3">
    <p>
      <strong>題名:<%= @video.body %></strong>
    </p>
    <p>
      <strong></strong>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @video.youtube_url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </p>
  </div>
</div>

<%= link_to '編集', edit_video_path(@video), class: "btn btn-lg btn-success" %> |
<%= link_to '戻る', videos_path, class: "btn btn-lg btn-default" %>