config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/privacy', to: "users#privacy"
  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  get   'contact'         => 'contact#index'     # 入力画面
  post  'contact/confirm' => 'contact#confirm'   # 確認画面
  post  'contact/thanks'  => 'contact#thanks'    # 送信完了画面
  
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  resources :users
  resources :videos
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @event = Event.new
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :body, :start_date, :end_date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "箇所") %> を入力してください</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_field :start_date, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_field :end_date, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", placeholder: "入力してください" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% provide(:title, 'Event Edit') %>
<h1>イベント編集</h1>

<%= render 'form', event: @event %>

<%= link_to '詳細', @event, class: "btn btn-lg btn-warning" %> |
<%= link_to '戻る', events_path, class: "btn btn-lg btn-default" %>

app/views/events/index.html.erb
<% provide(:title, 'Event Index') %>
<div class="row">
 <p>イベント</p>
  <div id="calendar" class="col-md-6">
  </div>
<div class="col-md-6">
  <table>
    <tbody>
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">イベントに参加</a>
            </h4>
          </div>
          <div id="collapse3" class="panel-collapse collapse">
            <div class="panel-body">
              <%= render 'form', event: @event %>
            </div>
          </div>
        </div>
      </div>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% provide(:title, 'Event Show') %>
<h1>イベント詳細</h1>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table class="table table-bordered" id="table-schedule">
        <tbody>
          <tr>
            <th class="active center">
              <p>
              <span><%= Event.human_attribute_name :start_date %></span>
              <span><td class="active"><%= l(@event.start_date, format: :short, default: '-') %><%= "~" %></span></td>
              <br><th class="active center"><span><%= Event.human_attribute_name :end_date %></span></th>
              <span><td class="active"><%= l(@event.end_date, format: :short, default: '-') %></span></td>
              </p>
            </th>
          </tr>
          <tr>
            <th class="active center col-md-2"><%= Event.human_attribute_name :title %></th>
            <td  class="active" colspan = "3"><%= @event.title %></td>
          </tr>
          <tr>
            <th class="active center"><%= Event.human_attribute_name :body %></th>
            <td  class="active" colspan = "3">
              <%= @event.body %>
            </td>
          </tr>
        </tbody>
      </table>
      <div>
        <%= link_to '戻る', events_path, class: "btn btn-lg btn-default" %>
        <%= link_to "編集", edit_event_path(@event), class: "btn btn-lg btn-success" %>
        <%= link_to "削除", event_path(id:@event.id), method: :delete,
        data: { confirm: "「#{@event.title}」を削除します。よろしいですか？" }, class: "btn btn-lg btn-danger" %>
      </div>
    </div>    
  </div>