config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/privacy', to: "users#privacy"
  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  get   'contact'         => 'contact#index'     # 入力画面
  post  'contact/confirm' => 'contact#confirm'   # 確認画面
  post  'contact/thanks'  => 'contact#thanks'    # 送信完了画面
  
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  resources :users
  resources :videos
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default" id = "header">
  <div class="container">
    <%= link_to "好きなイベントシステム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "ホーム", root_path, class: "glyphicon glyphicon-home header-list" %></li>
              <li><%= link_to "全てのユーザー", users_path, class: "glyphicon glyphicon-user header-list" %></li>
              <li class="dropdown">
              <a href="#" class="glyphicon glyphicon-th-list dropdown-toggle header-list" data-toggle="dropdown"
              id="dropdown-title">メニュー<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "イベント一覧", events_path, class: "glyphicon glyphicon-calendar" %></li>
                  <li><%= link_to "なにか", "#", class: "glyphicon glyphicon-briefcase" %></li>
                  <li><%= link_to "好きな動画", videos_path, class: "glyphicon glyphicon-facetime-video" %></li> 
                  <li><%= link_to "設定", user_path(current_user), class: "glyphicon glyphicon-cog" %></li>
                  <li><%= link_to "お問い合わせ", contact_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-off" %>
                  </li>
                </ul>
              </li>
        <% else %>
              <li><%= link_to "プライバシー ポリシー", privacy_path, class: "header-list" %></li>
              <li><%= link_to "ログイン", new_user_session_path, class: "header-list" %></li>
              <li><%= link_to "アカウント作成", new_user_registration_path, class: "header-list" %></li>
              <li class="dropdown">
              <a href="#" class="glyphicon glyphicon-th-list dropdown-toggle header-list" data-toggle="dropdown"
              id="dropdown-title">メニュー<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "イベント一覧", events_path, class: "glyphicon glyphicon-calendar" %></li>
                  <li><%= link_to "なにか", "#", class: "glyphicon glyphicon-briefcase" %></li>
                  <li><%= link_to "好きな動画", videos_path, class: "glyphicon glyphicon-facetime-video" %></li>
                  <li><%= link_to "お問い合わせ", contact_path %></li>
                </ul>
              </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- HTML shimがこの1行で収まる -->
    <%= render 'layouts/shim' %>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>